#!/usr/bin/env bash

# bootstrap installs things.
cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

# link dotfiles
link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

info 'Setup starting!'
# Set up dependences

# Check for Homebrew
check_brew() {
  if test $(which brew)
  then
    info 'Homebrew is installed'
    info 'Updating Homebrew.'
    success $(brew update)
  else
    info "Installing Homebrew for you."

    # Install the correct homebrew for each OS type
    if test "$(uname)" = "Darwin"
    then
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    elif test "$(expr substr $(uname -s) 1 5)" = "Linux"
    then
     ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
    fi
  fi
}

# Install apps
info 'Check brew status'
check_brew
brewfile="$HOME/.Brewfile"

info 'Install apps with brew.'
if test -f "$brewfile"; then
  info "Installing apps with Brewfile"
  brew bundle --global
fi

# Set system defaults
# info "Setup System Defaults"

# Configure git
info 'Configure git before we link dotfiles'
setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}

setup_gitconfig

# link files
info 'installing dotfiles'
link_dotfiles() {
  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}
link_dotfiles

# set up vim
setup_vim() {
  vundle_path="$DOTFILES_ROOT/vim/vim.symlink/bundle/Vundle.vim"
  vundle_repo="https://github.com/VundleVim/Vundle.vim.git"

  info "$vundle_path"

  if [ -d $vundle_path ]; then
      info "Updating Vundle..."

  #    cd $vundle_path
  #    git pull
  else
    info "Installing Vundle..."
    git clone "$vundle_repo" "$vundle_path"
  fi

  # update or install any new pluggins added to vim
  info 'Install Vundle Plugins..'
  vim +PluginInstall +qall
}
info 'Setup Editor, VIM.'
setup_vim

# set up oh-my-zsh
setup_zsh() {
  oh_my_zsh_repo="https://github.com/ohmyzsh/ohmyzsh.git"
  oh_my_zsh="$HOME/.oh-my-zsh"

  if [ ! -d $oh_my_zsh ]
  then
    info 'Install Oh-My-ZSH'
    git clone "$oh_my_zsh_repo" "$oh_my_zsh"
    pip3.8 install --user git+git://github.com/Lokaltog/powerline
  else
    info 'Already have oh-my-zsh'
  fi
}

info 'Setup ZSH'
setup_zsh

# Set up topics
# find the installers and run them iteratively
find . -name setup.sh | while read installer ; do sh -c "${installer}" ; done
success 'Setup is complete!'
